Data 412 add save points after each stage of transformations
getindata/dbt-airflow-factory pull request #61
Opened 2022-07-11 09:58 UTC by Imbruced

…irflow.
Abstract mapping nx graph to airflow tasks.

Resolves `DATA-412`

---
Keep in mind:
- [ ] Documentation updates
- [ ] [Changelog](CHANGELOG.md) updates

2022-07-11 10:14 UTC, p-pekala requested changes

2022-07-11 10:14 UTC, p-pekala commented on dbt_airflow_factory/tasks_builder/builder.py
> +    model_name: str
If you include schema and model_name into ModelExecutionTask it will the code will be simpler. Why do you want to wrapper?

2022-07-11 10:14 UTC, p-pekala commented on dbt_airflow_factory/tasks_builder/builder.py
> +        )
shouldn't be a `pass` instead of exception?

2022-07-11 10:14 UTC, p-pekala commented on dbt_airflow_factory/tasks_builder/builder.py
> +class DefaultConnectionMapper:
Shouldn't be class DefaultConnectionMapper(TaskConnectionMapper): ?

Why there is only one implementation? I thought you need an extra one?

2022-08-01 08:51 UTC, p-pekala requested changes

2022-08-01 08:51 UTC, p-pekala commented on dbt_airflow_factory/tasks_builder/graph.py
> +        if self.configuration.gateway.separation_schemas.__len__() >= 2:
does separation_schemas define a list of schemas that should be separated or schemas after which gateway should be created? I think the second makes more sense but implementation would be harder. What happens if someone forgets about one schema or some will be added and configuration not updated?

2022-08-01 08:51 UTC, p-pekala commented on dbt_airflow_factory/tasks_builder/graph.py
> +        if self.configuration.gateway.separation_schemas.__len__() >= 2:
and why are you using private __len__() instead len(...)?

2022-08-01 08:51 UTC, p-pekala commented on dbt_airflow_factory/tasks_builder/graph.py
> +                separation_layers = self.configuration.gateway.separation_schemas
You can move this line outside for - it will simplify also enumerate(....)

2022-08-01 08:51 UTC, p-pekala commented on pyproject.toml
> +requires = ["poetry-core>=1.0.0"]
we are not using poetry

2022-08-01 08:51 UTC, p-pekala commented on dbt_airflow_factory/tasks_builder/graph.py
> +        return is_valid_dep
why is that better? It was simpler previously.

2022-08-01 08:51 UTC, p-pekala commented on dbt_airflow_factory/tasks_builder/graph.py
> +            node_schema_index = self.configuration.gateway.separation_schemas.index(node_schema)
wyciągnąłbym to co pod ifem do osobnej metody bo to jest jakaś inna ścieżka

2022-08-01 08:51 UTC, p-pekala commented on dbt_airflow_factory/tasks_builder/gateway.py
> +        if dependency_node["schema"] == dataset_left and node["schema"] == dataset_right:
te dwie linijki wymagają przepchnięcia całego manifestu przez wsystkie metody jako parametr. Wolałbym jakiś obiekt stworzyć który by miał nazwę + schema.

2022-08-01 08:51 UTC, p-pekala commented on dbt_airflow_factory/tasks_builder/graph.py
> +        ):
dałbyś radę zamienić tego ifa na coś w stylu if _should_gateway_be_added(...)

2022-08-01 08:51 UTC, p-pekala commented on dbt_airflow_factory/tasks_builder/graph.py
> +                            node=node,
tutaj potrzebujesz tylko node["schema"] nie cały dict

2022-08-01 08:51 UTC, p-pekala commented on dbt_airflow_factory/tasks_builder/graph.py
> +class TaskGraphConfiguration:
Osobny plik na te dwie klaski?

2022-08-01 08:51 UTC, p-pekala commented on dbt_airflow_factory/tasks_builder/gateway.py
> +    manifest: dict, separation_layer_left: str, separation_layer_right: str
Could you wrap the left end right with some VO?

2022-08-07 20:01 UTC, Imbruced commented on dbt_airflow_factory/tasks_builder/graph.py
> +        if self.configuration.gateway.separation_schemas.__len__() >= 2:
Currently implementation is using approach between which schemas create such connections not after which it should be created. But you are right that approach that values should represent after which gateway should be added. But is this corner case is valid ? 
schemas: [a, b]
a.tab1 -> gateway -> c.tab2

2022-08-07 20:36 UTC, Imbruced commented on dbt_airflow_factory/tasks_builder/graph.py
> +        ):
pewnie :)

2022-08-07 20:54 UTC, Imbruced commented on dbt_airflow_factory/tasks_builder/graph.py
> +        return is_valid_dep
My bad, It was more complicated while I added new conditions but then I simplified them and that remains as an artifact.

2022-08-09 10:01 UTC, p-pekala requested changes
Please add documentation:
https://dbt-airflow-factory.readthedocs.io/en/latest/configuration.html
https://dbt-airflow-factory.readthedocs.io/en/latest/features.html

2022-08-09 10:01 UTC, p-pekala commented on dbt_airflow_factory/tasks_builder/graph.py
> +                        schema_name=manifest["nodes"][dep_node]["schema"],
Maybe it would be better to set manifest as a member of the class?

2022-08-22 10:43 UTC, p-pekala approved these changes

2022-09-02 13:37 UTC, merged