Data 369 integrate scheduling airbyte from airflow in the same dag as transformations
getindata/dbt-airflow-factory pull request #64
Opened 2022-08-07 23:33 UTC by Imbruced

`<description>`

Resolves `<issue nr here>`

---
Keep in mind:
- [ ] Documentation updates
- [ ] [Changelog](CHANGELOG.md) updates

2022-08-09 07:25 UTC, Santhin commented on dbt_airflow_factory/ingestion.py
> +class AbstractIngestionFactory:
What is the purpose of this class? You don't use it anywhere.

2022-08-09 08:05 UTC, p-pekala requested changes
Could you please add it to docs:
https://dbt-airflow-factory.readthedocs.io/en/latest/configuration.html
https://dbt-airflow-factory.readthedocs.io/en/latest/features.html

2022-08-25 08:00 UTC, Santhin approved these changes

2022-08-25 08:48 UTC, p-pekala approved these changes

2022-09-02 12:13 UTC, merged